### ISSUE TITLE
Object "on" has no more functionality

### ISSUE THREAD

**Issue by senger1985** [SwedishChef1/ioBroker.bosesoundtouch#24]
If I change the state from "true" to "false" the device does not switch off

**Comment by senger1985** [comment]
host.raspberrypi | 2018-11-05 23:57:36.486 | error | instance system.adapter.bosesoundtouch.0 terminated with code 1 ()
-- | -- | -- | --
host.raspberrypi | 2018-11-05 23:57:36.486 | error | Caught by controller[0]: at Function.Module._load (module.js:498:3)
host.raspberrypi | 2018-11-05 23:57:36.486 | error | Caught by controller[0]: at tryModuleLoad (module.js:506:12)
host.raspberrypi | 2018-11-05 23:57:36.486 | error | Caught by controller[0]: at Module.load (module.js:566:32)
host.raspberrypi | 2018-11-05 23:57:36.485 | error | Caught by controller[0]: at Object.Module._extensions..js (module.js:664:10)
host.raspberrypi | 2018-11-05 23:57:36.485 | error | Caught by controller[0]: at Module._compile (module.js:653:30)
host.raspberrypi | 2018-11-05 23:57:36.485 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.bosesoundtouch/lib/utils.js:79:17)
host.raspberrypi | 2018-11-05 23:57:36.485 | error | Caught by controller[0]: at require (internal/module.js:11:18)
host.raspberrypi | 2018-11-05 23:57:36.485 | error | Caught by controller[0]: at Module.require (module.js:597:17)
host.raspberrypi | 2018-11-05 23:57:36.484 | error | Caught by controller[0]: at Function.Module._load (module.js:475:25)
host.raspberrypi | 2018-11-05 23:57:36.484 | error | Caught by controller[0]: at Function.Module._resolveFilename (module.js:548:15)
host.raspberrypi | 2018-11-05 23:57:36.484 | error | Caught by controller[0]: Error: Cannot find module 'D:\Harald\Documents\JavaScript\iobroker\node_modules\iobroker.js-controller/lib/adapter.js'
host.raspberrypi | 2018-11-05 23:57:36.484 | error | Caught by controller[0]: ^
host.raspberrypi | 2018-11-05 23:57:36.483 | error | Caught by controller[0]: throw err;
host.raspberrypi | 2018-11-05 23:57:36.482 | error | Caught by controller[0]: module.js:550

**Comment by castorlighting** [comment]
Just use the actual github version. In the release which you install via iobroker it says in the utlis.js
`**
 * looks for js-controller home folder
 *
 * @param {boolean} isInstall
 * @returns {string}
 */
function getControllerDir(isInstall) {
    // Find the js-controller location
    return "D:\\Harald\\Documents\\JavaScript\\iobroker\\node_modules\\iobroker.js-controller"`

**Comment by Apollon77** [comment]
Correct, NPM version is broken!!
@SwedishChef1 pleass release new version!!
